#debug: true
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://admin@admin:mano-eureka:8761/eureka/
logging:
  level:
    org:
      springframework: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  elastic:
    metrics:
      export:
        host: http://mano-es:9200
        index: mano-metrics-alarm
        index-date-format: yyyy-MM-dd
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://mano-zipkin:9411/api/v2/spans

mano:
  monitoring:
    url: "http://mano-mon:8080/"

spring:
  application:
    name: mano-alarm
  artemis:
    broker-url: tcp://mano-artemis:61616
    user: artemis
    password: simetraehcapa
  boot:
    admin:
      client:
        enabled: false
        username: admin
        password: admin
        url:
        - http://mano-admin:8081
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://mano-db:5432/mano_alarm
    username: mano_alarm
    password: mano
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always

